language: python
python: 3.9
before_install:
  - python --version
  - python -m pip install --upgrade pip
  - pip install --user -r requirements.txt --use-feature=2020-resolver
env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
script: pytest
deploy:
  provider: heroku
  api_key:
    secure: "sBJANSP3WSa70I8LkdGihbj4UcIQi0LgR9y4ux+pwSaygkMCMVNPTqhjs6qUBYMe17IjYxoMkxubvsUYeqR1x0ohQ8sL5qOqrv+xvZiPOUnY0UY33EOIOS1wlX72ki/EuOZxnE+xpIVNyvzzZQdgZyPYNwD+UAnokNgAnhe3izjNAFR7XDSRII/IerTSUo3sgpa7aChnYhT7h9WQhUhSw40pgZj5khB7MnQUIfp/5Btk0S15Nuu6hjYPEfCW4CCwlZGot910ioRhUTvdTDVkrf0LFj8Mk69joteerkpq196AZ1lBuScKjPWqtDeqZ02RL7lXuPje9Foul6GLRjDxzgDtDxnP85DfU1hDPyYgaGXKu9OQETumv0z0sUVSf83N9REiW1kHs0370twX9PQmrs8I6x/rMO7QTqmUvYbCy/efVADl2hPU7ovFPv2gQvLRHkAr3xsbcmGCxleqkXQuEfxPmOp1r+o2+jcg1kyO5E8F+1VqLGHbe27SYVnvNt0CQl2LAhWKLO93Ilm5MsAYpP0LZVDJeeQhaTPqQ3yyvhPQGhqP1rzAf2nU5NPQY5EM/KcQwPqJy4ZzmprfnVYre4vC99uENL26NNgE4Aoj3D+w6Qdq48t3Cctb2VKy0V+zz/fbIlrzg/ifuEVXm110Atj6MdBY5mfKe2vURP4C9xQ="
  app: adhoc-pipeline
  on:
    repo: raahoolkumeriya/fastapi-pipline
after_success:  
  - 'curl http://adhoc-pipeline.herokuapp.com'