language: python
jobs:
  include:
    - name: "Python 3.9.0 on Xenial Linux"
      python: 3.9           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.6.10 on FreeBSD"
      os: freebsd
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
      install:
      - pip install --user -r requirements.txt --use-feature=2020-resolver
    - stage: pytests
      script: 
      - pytest
    - stage: deploy to heroku
      script: skip
      deploy: &heroku
        provider: heroku
        app: adhoc-pipeline
        api_key: f3ae7bed-c559-4b7d-8422-1767e933af1b
    - stage: Test App
      script: 'curl http://adhoc-pipeline.herokuapp.com'